name: IMHERE_GITHUB_ACTION_CI

on:
  pull_request:
    branches:
      - "**"
      - "!main"

jobs:
  test:
    name: Test
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK 25
        uses: actions/setup-java@v6
        with:
          java-version: "25"
          distribution: "corretto"

      - name: Cache Gradle packages
        uses: actions/cache@v6
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            gradle-${{ runner.os }}-

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Test deployment scripts
        run: |
          bash -n infra/scripts/*.sh infra/scripts/setting-ec2 infra/scripts/deploy-sub-tasks/*.sh infra/scripts/deploy-sub-tasks/tls-sub-tasks/*.sh

      - name: Run tests
        run: ./gradlew test
        env:
          TESTCONTAINERS_RYUK_DISABLED: "true"


      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results
          path: build/reports/tests/test/

      - name: Upload JaCoCo report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: jacoco-report
          path: build/jacocoHtml/
